### PR TITLE
Fix recent workspaces section in navbar

### LINKED ISSUE #17452: [new UD] Fix recent workspaces in sidebar
We need to provide fixes for recent workspaces section in sidebar to provide a correct behaviour to that nav items that is

- sort recent workspaces in descending order of update time
- handle adding and removing workspaces
- handle workspace status changes

### PR DESCRIPTION
**Pull request by akurinnoy**
This PR provides fixes for the recent workspaces section in navigation bar in order to properly sort navigation items and update workspace status indicators.

fixes https://github.com/eclipse/che/issues/17452

### CODE REVIEW

File: src/pages/WorkspacesList/index.tsx [hunk 1]
```diff
@@ -45,51 +47,95 @@ export class WorkspacesList extends React.PureComponent<Props> {
...
+      <span key={`${workspace.id}_5`}>
+        {actions}
+      </span>
+    ]);
   }
 
-  // This method is called when the route parameters change
-  public componentDidUpdate(): void {
-    this.ensureDataFetched();
+  private buildActions(workspace: che.Workspace): React.ReactNode {
```
Comment (olexii4) [inline src/pages/WorkspacesList/index.tsx:87]: You are using ```WorkspaceStatus[workspace.status]``` more than 5 times. Let's create a constant.
For example:
```
const status = WorkspaceStatus[workspace.status];
if (status === WorkspaceStatus.STARTING || status === WorkspaceStatus.RUNNING) {
...
```

Comment (akurinnoy) [reply src/pages/WorkspacesList/index.tsx:87]: makes sense, I'll provide a fixup

File: src/store/Workspaces/index.ts [hunk 2]
```diff
@@ -197,20 +209,15 @@ export const actionCreators: ActionCreators = {
   },
 
   stopWorkspace: (workspaceId: string): AppThunk<KnownAction, Promise<void>> => async (dispatch): Promise<void> => {
-    dispatch({ type: 'REQUEST_WORKSPACES' });
-
     try {
-      const workspace = await WorkspaceClient.restApiClient.stop(workspaceId);
-      dispatch({ type: 'UPDATE_WORKSPACE', workspace });
```
Comment (olexii4) [inline src/store/Workspaces/index.ts:204]: ```dispatch({ type: 'UPDATE_WORKSPACE', workspace });``` was removed.
In this case, if something happens with WebSocket connection we will lose status changes ```
start -> stopping``` and leave a possibility to send several requests to the server-side. It will generate lots of errors.
WDYT?

File: src/store/Workspaces/index.ts [hunk 3]
```diff
@@ -317,6 +324,16 @@ export const reducer: Reducer<State> = (state: State | undefined, action: KnownA
...
       });
+    case 'UPDATE_WORKSPACE_STATUS':
+      return createState(state, {
+        workspaces: state.workspaces.map(workspace => {
+          if (workspace.id !== action.workspaceId) {
+            return workspace;
+          }
+          workspace.status = action.status;
+          return workspace;
+        })
```
Comment (olexii4) [inline src/store/Workspaces/index.ts:334]: I think it can be simpler:
```
       workspace => {
          if (workspace.id !== action.workspaceId) {
            return workspace;
          }
          workspace.status = action.status;
          return workspace;
        })
```
=>

```
       workspace => {
          if (workspace.id === action.workspaceId) {
            workspace.status = action.status;
          }
          return workspace;
        })
```

File: src/store/Workspaces/index.ts (hunk 2 above)
Comment (akurinnoy) [reply src/store/Workspaces/index.ts:204]: `restApiClient.stop()` returns `Promise<void>` hence we don't lose anything here.

**Review by olexii4 — APPROVED** [review]
LGTM

File: src/store/Workspaces/index.ts (hunk 3 above)
Comment (akurinnoy) [reply src/store/Workspaces/index.ts:334]: good point, thanks!

File: src/store/Workspaces/index.ts (hunk 2 above)
Comment (olexii4) [reply src/store/Workspaces/index.ts:204]: I disagree with you:

https://github.com/eclipse/che-workspace-client/blob/master/src/rest/remote-api.ts#L82
https://github.com/eclipse/che-workspace-client/blob/master/src/rest/remote-api.ts#L301
```
   /**
     * Stops a workspace.
     *
     * @param {string} workspaceId a workspace ID.
     * @returns {Promise<any>}
     */
    public stop(workspaceId: string): Promise<any> {
        return new Promise<any>((resolve, reject) => {
            this.remoteAPI.stop(workspaceId)
                .then((response: AxiosResponse<any>) => {
                    resolve(response.data);
                })
                .catch((error: AxiosError) => {
                    reject(new RequestError(error));
                });
        });
    }
```

Comment (akurinnoy) [reply src/store/Workspaces/index.ts:204]: Correct me if I'm wrong, but this request resolves with `204 No Content`.

https://github.com/eclipse/che/blob/b2e83ac1a411a15e45ea90f0aebf6072c0723b35/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L398-L414
```java
  @DELETE
  @Path("/{id}/runtime")
  @ApiOperation(
      value = "Stop the workspace",
      notes =
          "This operation can be performed only by the workspace owner."
              + "The workspace stops asynchronously")
  @ApiResponses({
    @ApiResponse(code = 204, message = "The workspace is stopping"),
    @ApiResponse(code = 404, message = "The workspace with specified id doesn't exist"),
    @ApiResponse(code = 403, message = "The user is not workspace owner"),
    @ApiResponse(code = 500, message = "Internal server error occurred")
  })
  public void stop(@ApiParam("The workspace id") @PathParam("id") String id)
      throws ForbiddenException, NotFoundException, ServerException, ConflictException {
    workspaceManager.stopWorkspace(id, emptyMap());
  }
```

**Review by olexii4 — APPROVED** [review]
