### PR TITLE
Fix unneeded things appear during autocomplete

### LINKED ISSUE #17744: [new UD] Unneeded things appear during autocomplete
### Describe the bug

For some reason, unneeded things appear, after adding  ‘components:’ with devfile editor completion.

### Steps to reproduce

1. Open Get Started page.
2. Select Custom Workspace.
3. Put the cursor into the empty line in the Devfile Editor.
4. Press Ctrl +  Space.
5. Select the ‘components’. It will be added to devfile.

And we will see next:
``` yaml
...
components:
  - mountSources: false
```

### Expected behavior

``` yaml
...
components: 
```

### Screenshots

Screenshot from 2020-06-01 15-30-59
Screenshot from 2020-06-01 15-31-46

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
Fix unneeded things appear during autocomplete.

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/17744

Screenshot from 2020-08-28 16-24-10
Screenshot from 2020-08-28 16-45-59
Screenshot from 2020-08-28 16-43-57

### CODE REVIEW

File: src/components/DevfileEditor/index.tsx [hunk 1]
```diff
@@ -102,6 +102,13 @@ export class DevfileEditor extends React.PureComponent<Props, State> {
     const items = this.props.plugins.plugins;
     const components = jsonSchema && jsonSchema.properties ? jsonSchema.properties.components : undefined;
     if (components) {
+      const mountSources = components.items.properties.mountSources;
+
+      // TODO remove this temporary solution
```
Comment (sleshchenko) [inline src/components/DevfileEditor/index.tsx]: means there is some plan how to get rid of that... Do we really have that?
If there is no any plan - instead I would write a comment that explains why it's here, something like
> mount sources is specific only for some of component types but always appears  
> patch schema and remove default value for boolean mount sources to avoid their appearing during the completion

**Review by sleshchenko — APPROVED** [review]
Seems to work as expected. 
Does it really fully fixes the referenced issue? Could we also do the same for the Che Dashboard?

File: src/components/DevfileEditor/index.tsx (hunk 1 above)
Comment (olexii4) [reply src/components/DevfileEditor/index.tsx]: Thanks. Done

**Comment by olexii4** [comment]
@sleshchenko I have done the same for the Che Dashboard

**Review by akurinnoy — APPROVED** [review]
